CustomRuleSet:
  UseAssertJOnly:
    active: true
  DescriptiveTestFunctions:
    active: true
  NoDataClassEntity:
    active: true
  ArgumentsOfSameType:
    active: true
  JPAEagerLoading:
    active: true
